
#+OPTIONS: \n:t

[[https://asciinema.org/a/0njIqEMp5DKaKJkdlFfiRF1iI][asciinema]]

* Analyse Fréquentielle

[[https://fr.wikipedia.org/wiki/Fr%C3%A9quence_d%27apparition_des_lettres_en_fran%C3%A7ais][Fréquence d'apparition des lettres en français]] 
[[https://en.wikipedia.org/wiki/Letter_frequency][Letter Frequency]] 
[[https://en.wikipedia.org/wiki/Etaoin_shrdlu][Etaoin shrdlu]] 

[[https://fr.wikipedia.org/wiki/American_Standard_Code_for_Information_Interchange][ASCII]] 

* (Optionnel : récupérer les arguments de la ligne de commande)

#+begin_src js
process.argv
#+end_src

Retourne le tableau des arguments passés en ligne de commande 

#+begin_src js
process.argv[0]
#+end_src

Pour récupérer le premier argument.

* Variables 

** text 

Un tableau dont chaque élément est un caractère (majuscule) ou bien un espace.

** key

La clé (sous la forme d'un nombre).
Cette variable n'est utile que pour chiffrer uniquement !

** alphabet

Un tableau de 26 éléments. Chaque "case" représente le nombre de fois qu'une lettre est présente dans le texte.
Example : 
alphabet[0] est la première case du tableau, la valeur représente le nombre de 'A' dans le texte chiffré.
alphabet[1] est la deuxième case du tableau, la valeur représente le nombre de 'B' dans le texte chiffré.
…
alphabet[25] est la vingt-sixième case du tableau, la valeur représente le nombre de 'Z' dans le texte chiffré.

** etaoinshrdlu

Un tableau avec les lettres les plus fréquentes en anglais. (De longueur 12)

** freqLetterCode

C'est l'index du tableau alphabet pour la lettre la plus présente dans le texte chiffré.

** keys

Un tableau de même longueur que etaoinshrdlu qui contient les décalages (clés) les plus probables.
Cette variable n'est utile que pour dechiffrer uniquement !

* Fonctions

** encryptChar

Paramètres : 
- c : charactère
- n : nombre entier

Renvoie : Le code décimal ASCII de c + n, en restant entre 'A' et 'Z'

Fonction qui chiffre un caractère c en le décalant de n.

** cypher

Paramètres : 
- tab : tableau de charactères
- key : nombre entier

Renvoie : une chaine de charactère

Fonction qui chiffre un message à partir du tableau tab avec la clé key.

** decypher

L'inverse de la fonction cypher.

** listDecypher

Paramètre : 
- tab : tableau de charactères

Renvoie : rien, affiche 12 textes déchiffrés avec les 12 clés générées.

Déchiffre le texte chiffré avec les clés les plus probables (hypothèse : texte en anglais).


